### ISSUE TITLE
Questions about atom-specific buckingham and switch from exp-6 to 12-6?

### ISSUE THREAD

**Issue by mrshirts** [jayponder/tinker#31]
Looking through the buckingham potential code in ebuck, it seems like the A, B, and C are global parameters, rather than per-atomic parameters. We're trying to translate something from gromacs, the system has three independent parameters A_ij, B_ij, C_ij. Since the sigma and epsilon can be set for these particles, that gives two parameters that one can adjust, so one can sort of set two of them:
i.e., the energy is:

e = epsilon_ij [abuck * exp(-bbuck r/sigma_ij) - cbuck * sigma_ij^12/ r^12

Which maps to:

A_ij = epsilon_ij *abuck
B_ij = bbuck/sigma_ij
C_ij = epsilon_ij * cbuck * sigma_ij^12

So for any given A_ij, B_ij, C_ij, you arbitrarily set A_ij and C_ij OR B_ij and C_ij, using epsilon_ij and sigma_ij but not all three independently.  Am I missing something, and is there a way to do this?

I'm willing to do some work to implement this if necessary, if there is not a way to do this already.

Also, I see that it switches to a standard 12-6 potential outside of a certain cutoff.  Is this just for speed, since at a certain distance, r^-12 and exp(-r)?

**Comment by jayponder** [comment]
Hi Michael,

As you note, the "ebuck" potential in TINKER is not a fully general "Buckingham" potential with 3 parameters. It is instead a more limited 2-parameter so-called Buckingham-Hill potential that implements the form used (long, long ago...) in Lou Allinger's MM series of force fields (MM2, MM3, MM4...). Unless I'm missing something, it would not be too difficult to generalize this energy term to the "full" Buckingham potential. But I'd certainly want to try to maintain easy access to the current Buckingham-Hill form from any modification. If you want to give this a shot, by all means go ahead. Otherwise, I could try to get to it somewhere in the near-to-medium time frame.

Jay
